name: Compile LaTeX

on:
  push:
    branches: [ "**" ] 

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: CV/Mohamed_Wael_CV.tex  
          shell_escape: true

      - name: Upload PDF artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: Mohamed_Wael_CV
          path: CV/Mohamed_Wael_CV.pdf 

      - name: Commit and push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated PDF commit"
          file_pattern: CV/Mohamed_Wael_CV.pdf 
          skip_dirty_check: false
